import type { Customer, Project, CalendarEvent, EmailThread, TeamMember, DashboardStats } from "./types";

export const teamMembers: TeamMember[] = [
  { id: "1", name: "Jake Mercer", role: "Project Manager", email: "jake@shorebreakelectric.com", color: "#f97316" },
  { id: "2", name: "Ana Torres", role: "Lead Installer", email: "ana@shorebreakelectric.com", color: "#3b82f6" },
  { id: "3", name: "Ryan Nguyen", role: "Electrician", email: "ryan@shorebreakelectric.com", color: "#8b5cf6" },
  { id: "4", name: "Sarah Kim", role: "Sales Rep", email: "sarah@shorebreakelectric.com", color: "#10b981" },
  { id: "5", name: "Tom Walsh", role: "Site Assessor", email: "tom@shorebreakelectric.com", color: "#f59e0b" },
];

export const customers: Customer[] = [
  {
    id: "c1", name: "David & Lisa Chen", email: "david.chen@gmail.com", phone: "(619) 555-0182",
    address: "1420 Ocean View Dr", city: "Encinitas", state: "CA", zip: "92024",
    type: "residential", status: "active", source: "referral",
    createdAt: "2025-11-15", lastContact: "2026-04-28", projectCount: 2, totalValue: 42500,
    notes: "Referred by the Martins. Interested in battery backup as well."
  },
  {
    id: "c2", name: "Sunrise Surf & Sport", email: "mgr@sunrisesurfsport.com", phone: "(760) 555-0347",
    address: "855 Coast Hwy 101", city: "Solana Beach", state: "CA", zip: "92075",
    type: "commercial", status: "active", source: "google",
    createdAt: "2025-12-02", lastContact: "2026-05-01", projectCount: 1, totalValue: 87000,
    notes: "Commercial roof needs structural assessment before install."
  },
  {
    id: "c3", name: "Maria Gonzalez", email: "mariag@yahoo.com", phone: "(858) 555-0924",
    address: "312 Hillside Rd", city: "Vista", state: "CA", zip: "92083",
    type: "residential", status: "lead", source: "door-to-door",
    createdAt: "2026-04-20", lastContact: "2026-04-20", projectCount: 0, totalValue: 0,
  },
  {
    id: "c4", name: "Pacific View HOA", email: "board@pacificviewhoa.com", phone: "(760) 555-0561",
    address: "2000 Pacific View Dr", city: "Carlsbad", state: "CA", zip: "92008",
    type: "commercial", status: "active", source: "referral",
    createdAt: "2026-01-10", lastContact: "2026-04-30", projectCount: 3, totalValue: 215000,
  },
  {
    id: "c5", name: "Brett & Jess Thompson", email: "brett.thompson@gmail.com", phone: "(619) 555-0713",
    address: "78 Coastal Oaks Ln", city: "Del Mar", state: "CA", zip: "92014",
    type: "residential", status: "complete", source: "website",
    createdAt: "2025-09-01", lastContact: "2026-03-15", projectCount: 1, totalValue: 31200,
  },
  {
    id: "c6", name: "North County Dental Group", email: "admin@ncdentalgroup.com", phone: "(760) 555-0289",
    address: "450 Marketplace Dr", city: "San Marcos", state: "CA", zip: "92069",
    type: "commercial", status: "lead", source: "google",
    createdAt: "2026-04-28", lastContact: "2026-04-28", projectCount: 0, totalValue: 0,
  },
  {
    id: "c7", name: "Rick Sandoval", email: "rsandoval@icloud.com", phone: "(760) 555-0445",
    address: "911 Sunset Ridge", city: "Oceanside", state: "CA", zip: "92057",
    type: "residential", status: "active", source: "referral",
    createdAt: "2026-02-14", lastContact: "2026-04-25", projectCount: 1, totalValue: 28900,
  },
  {
    id: "c8", name: "Coastal Brew Co.", email: "owner@coastalbrewco.com", phone: "(760) 555-0812",
    address: "1100 Industrial Ave", city: "Escondido", state: "CA", zip: "92029",
    type: "commercial", status: "active", source: "website",
    createdAt: "2026-03-05", lastContact: "2026-04-29", projectCount: 1, totalValue: 64500,
  },
];

export const projects: Project[] = [
  {
    id: "p1", projectNumber: "SBE-2026-041", title: "Chen Residence — 12.4kW Solar + Battery",
    customerId: "c1", customerName: "David & Lisa Chen",
    address: "1420 Ocean View Dr, Encinitas, CA 92024",
    type: "solar+electrical", stage: "installation", value: 42500, systemSize: 12.4,
    startDate: "2026-03-01", targetDate: "2026-05-15", assignedTo: "2",
    tags: ["battery", "hoa-approved", "tesla-powerwall"],
    progress: 75, priority: "high",
    permits: [
      { id: "per1", type: "Building Permit", status: "approved", submittedDate: "2026-03-20", approvedDate: "2026-04-10", number: "BP-2026-3821" },
      { id: "per2", type: "Electrical Permit", status: "approved", submittedDate: "2026-03-20", approvedDate: "2026-04-12", number: "EP-2026-1104" },
    ],
    tasks: [
      { id: "t1", title: "Roof inspection complete", completed: true },
      { id: "t2", title: "Equipment ordered & delivered", completed: true },
      { id: "t3", title: "Racking installation", completed: true },
      { id: "t4", title: "Panel installation", completed: false, dueDate: "2026-05-06" },
      { id: "t5", title: "Inverter & battery wiring", completed: false, dueDate: "2026-05-08" },
      { id: "t6", title: "Final inspection scheduled", completed: false, dueDate: "2026-05-12" },
    ],
    files: [
      { id: "f1", name: "Site Survey.pdf", type: "pdf", size: 2400000, url: "#", uploadedAt: "2026-03-05", driveId: "drive_001" },
      { id: "f2", name: "System Design.pdf", type: "pdf", size: 5100000, url: "#", uploadedAt: "2026-03-15", driveId: "drive_002" },
    ],
    lastUpdated: "2026-05-01",
  },
  {
    id: "p2", projectNumber: "SBE-2026-038", title: "Sunrise Surf & Sport — 48kW Commercial Solar",
    customerId: "c2", customerName: "Sunrise Surf & Sport",
    address: "855 Coast Hwy 101, Solana Beach, CA 92075",
    type: "solar", stage: "permitting", value: 87000, systemSize: 48,
    startDate: "2026-02-10", targetDate: "2026-06-30", assignedTo: "1",
    tags: ["commercial", "flat-roof", "string-inverter"],
    progress: 45, priority: "high",
    permits: [
      { id: "per3", type: "Building Permit", status: "submitted", submittedDate: "2026-04-01", number: "BP-2026-4102" },
      { id: "per4", type: "Electrical Permit", status: "submitted", submittedDate: "2026-04-01" },
      { id: "per5", type: "SDG&E Interconnection", status: "pending" },
    ],
    tasks: [
      { id: "t7", title: "Structural engineering report", completed: true },
      { id: "t8", title: "Electrical design drawings", completed: true },
      { id: "t9", title: "Permit applications submitted", completed: true },
      { id: "t10", title: "Permit approval follow-up", completed: false, dueDate: "2026-05-10" },
    ],
    files: [],
    lastUpdated: "2026-04-30",
  },
  {
    id: "p3", projectNumber: "SBE-2026-044", title: "Sandoval — 8.2kW Solar",
    customerId: "c7", customerName: "Rick Sandoval",
    address: "911 Sunset Ridge, Oceanside, CA 92057",
    type: "solar", stage: "engineering", value: 28900, systemSize: 8.2,
    startDate: "2026-04-01", targetDate: "2026-06-01", assignedTo: "5",
    tags: ["shingle-roof", "microinverter"],
    progress: 30, priority: "medium",
    permits: [
      { id: "per6", type: "Building Permit", status: "pending" },
    ],
    tasks: [
      { id: "t11", title: "Site assessment complete", completed: true },
      { id: "t12", title: "System design in progress", completed: false, dueDate: "2026-05-08" },
      { id: "t13", title: "Submit permit applications", completed: false, dueDate: "2026-05-15" },
    ],
    files: [],
    lastUpdated: "2026-04-25",
  },
  {
    id: "p4", projectNumber: "SBE-2026-042", title: "Coastal Brew Co. — 32kW Solar + EV Charging",
    customerId: "c8", customerName: "Coastal Brew Co.",
    address: "1100 Industrial Ave, Escondido, CA 92029",
    type: "solar+electrical", stage: "site-assessment", value: 64500, systemSize: 32,
    startDate: "2026-04-15", targetDate: "2026-07-31", assignedTo: "5",
    tags: ["ev-charging", "commercial", "industrial"],
    progress: 15, priority: "medium",
    permits: [],
    tasks: [
      { id: "t14", title: "Initial site visit scheduled", completed: true },
      { id: "t15", title: "Roof and electrical assessment", completed: false, dueDate: "2026-05-07" },
      { id: "t16", title: "Load analysis", completed: false, dueDate: "2026-05-12" },
    ],
    files: [],
    lastUpdated: "2026-04-29",
  },
  {
    id: "p5", projectNumber: "SBE-2026-039", title: "Pacific View HOA — Phase 1 Carport Solar",
    customerId: "c4", customerName: "Pacific View HOA",
    address: "2000 Pacific View Dr, Carlsbad, CA 92008",
    type: "solar", stage: "proposal", value: 78000, systemSize: 64,
    startDate: "2026-04-20", targetDate: "2026-08-15", assignedTo: "4",
    tags: ["carport", "commercial", "hoa"],
    progress: 10, priority: "high",
    permits: [],
    tasks: [
      { id: "t17", title: "Proposal draft sent", completed: true },
      { id: "t18", title: "Board presentation", completed: false, dueDate: "2026-05-12" },
      { id: "t19", title: "Contract signing", completed: false },
    ],
    files: [],
    lastUpdated: "2026-04-30",
  },
  {
    id: "p6", projectNumber: "SBE-2026-035", title: "Thompson Residence — 9.8kW Solar",
    customerId: "c5", customerName: "Brett & Jess Thompson",
    address: "78 Coastal Oaks Ln, Del Mar, CA 92014",
    type: "solar", stage: "complete", value: 31200, systemSize: 9.8,
    startDate: "2025-10-01", targetDate: "2026-01-15", completedDate: "2026-03-10",
    assignedTo: "2",
    tags: ["residential", "string-inverter", "HOA-approved"],
    progress: 100, priority: "low",
    permits: [
      { id: "per7", type: "Building Permit", status: "approved", number: "BP-2025-8821" },
      { id: "per8", type: "Electrical Permit", status: "approved", number: "EP-2025-3392" },
    ],
    tasks: [],
    files: [],
    lastUpdated: "2026-03-10",
  },
  {
    id: "p7", projectNumber: "SBE-2026-047", title: "Gonzalez — Initial Consultation",
    customerId: "c3", customerName: "Maria Gonzalez",
    address: "312 Hillside Rd, Vista, CA 92083",
    type: "solar", stage: "lead", value: 0,
    startDate: "2026-04-20", targetDate: "2026-06-01", assignedTo: "4",
    tags: ["residential"],
    progress: 5, priority: "low",
    permits: [],
    tasks: [
      { id: "t20", title: "Send intro email", completed: true },
      { id: "t21", title: "Schedule consultation call", completed: false, dueDate: "2026-05-07" },
    ],
    files: [],
    lastUpdated: "2026-04-20",
  },
  {
    id: "p8", projectNumber: "SBE-2026-046", title: "Pacific View HOA — Phase 2 Panel Upgrade",
    customerId: "c4", customerName: "Pacific View HOA",
    address: "2000 Pacific View Dr, Carlsbad, CA 92008",
    type: "electrical", stage: "inspection", value: 42000,
    startDate: "2026-03-01", targetDate: "2026-05-10", assignedTo: "3",
    tags: ["panel-upgrade", "200A", "hoa"],
    progress: 90, priority: "high",
    permits: [
      { id: "per9", type: "Electrical Permit", status: "approved", number: "EP-2026-0892" },
    ],
    tasks: [
      { id: "t22", title: "Panel upgrade complete", completed: true },
      { id: "t23", title: "Final inspection scheduled", completed: true },
      { id: "t24", title: "City sign-off", completed: false, dueDate: "2026-05-07" },
    ],
    files: [],
    lastUpdated: "2026-05-02",
  },
];

export const calendarEvents: CalendarEvent[] = [
  {
    id: "ev1", title: "Chen Panel Installation — Day 1",
    start: "2026-05-06T08:00:00", end: "2026-05-06T17:00:00",
    projectId: "p1", customerId: "c1", type: "installation",
    location: "1420 Ocean View Dr, Encinitas, CA",
    attendees: ["ana@shorebreakelectric.com", "ryan@shorebreakelectric.com"],
  },
  {
    id: "ev2", title: "Coastal Brew — Site Assessment",
    start: "2026-05-07T10:00:00", end: "2026-05-07T13:00:00",
    projectId: "p4", customerId: "c8", type: "assessment",
    location: "1100 Industrial Ave, Escondido, CA",
    attendees: ["tom@shorebreakelectric.com"],
  },
  {
    id: "ev3", title: "Pacific View HOA — City Inspection",
    start: "2026-05-07T14:00:00", end: "2026-05-07T15:00:00",
    projectId: "p8", customerId: "c4", type: "inspection",
    location: "2000 Pacific View Dr, Carlsbad, CA",
    attendees: ["ryan@shorebreakelectric.com"],
  },
  {
    id: "ev4", title: "Sandoval System Design Review",
    start: "2026-05-08T09:00:00", end: "2026-05-08T10:00:00",
    projectId: "p3", type: "meeting",
    attendees: ["jake@shorebreakelectric.com", "tom@shorebreakelectric.com"],
  },
  {
    id: "ev5", title: "Chen Panel Installation — Day 2",
    start: "2026-05-08T08:00:00", end: "2026-05-08T17:00:00",
    projectId: "p1", customerId: "c1", type: "installation",
    location: "1420 Ocean View Dr, Encinitas, CA",
    attendees: ["ana@shorebreakelectric.com", "ryan@shorebreakelectric.com"],
  },
  {
    id: "ev6", title: "HOA Board Presentation — Pacific View",
    start: "2026-05-12T18:00:00", end: "2026-05-12T20:00:00",
    projectId: "p5", customerId: "c4", type: "meeting",
    location: "2000 Pacific View Dr, Carlsbad, CA",
    attendees: ["jake@shorebreakelectric.com", "sarah@shorebreakelectric.com"],
  },
  {
    id: "ev7", title: "Chen Final Inspection",
    start: "2026-05-14T09:00:00", end: "2026-05-14T11:00:00",
    projectId: "p1", customerId: "c1", type: "inspection",
    location: "1420 Ocean View Dr, Encinitas, CA",
  },
  {
    id: "ev8", title: "North County Dental — Initial Consultation",
    start: "2026-05-09T11:00:00", end: "2026-05-09T12:00:00",
    customerId: "c6", type: "meeting",
    attendees: ["sarah@shorebreakelectric.com"],
  },
];

export const emailThreads: EmailThread[] = [
  {
    id: "em1", subject: "Re: Chen Installation — Schedule Confirmation",
    snippet: "Hi Jake, we're confirmed for Tuesday the 6th. Ana will have the team there by 8am...",
    from: "David Chen", fromEmail: "david.chen@gmail.com",
    to: ["jake@shorebreakelectric.com"],
    date: "2026-05-02T14:32:00", unread: true, starred: true,
    labels: ["project", "installation"], projectId: "p1", customerId: "c1",
    messageCount: 8,
  },
  {
    id: "em2", subject: "Sunrise Surf — Permit Status Update",
    snippet: "We checked with the City of Solana Beach — they expect to issue the building permit within...",
    from: "Tom Walsh", fromEmail: "tom@shorebreakelectric.com",
    to: ["jake@shorebreakelectric.com"],
    date: "2026-05-01T10:15:00", unread: true, starred: false,
    labels: ["permitting", "internal"], projectId: "p2",
    messageCount: 3,
  },
  {
    id: "em3", subject: "Quote Request — Solar + EV Charging",
    snippet: "Hello, I'm the owner of North County Dental Group. We have a 5,000 sq ft office and we're...",
    from: "Dr. Kevin Park", fromEmail: "admin@ncdentalgroup.com",
    to: ["info@shorebreakelectric.com"],
    date: "2026-04-28T08:44:00", unread: true, starred: true,
    labels: ["lead", "inquiry"], customerId: "c6",
    messageCount: 1,
  },
  {
    id: "em4", subject: "Pacific View HOA — Phase 2 Inspection Tomorrow",
    snippet: "Ryan, just a reminder that the city inspector is coming tomorrow at 2pm. Please make sure...",
    from: "Jake Mercer", fromEmail: "jake@shorebreakelectric.com",
    to: ["ryan@shorebreakelectric.com"],
    date: "2026-05-01T16:00:00", unread: false, starred: false,
    labels: ["inspection", "internal"], projectId: "p8", customerId: "c4",
    messageCount: 2,
  },
  {
    id: "em5", subject: "SDG&E Interconnection Application — Action Needed",
    snippet: "Your interconnection application for Sunrise Surf & Sport (Case #IC-2026-4489) requires additional...",
    from: "SDG&E Interconnection Team", fromEmail: "interconnection@sdge.com",
    to: ["jake@shorebreakelectric.com"],
    date: "2026-04-30T09:22:00", unread: false, starred: true,
    labels: ["utility", "interconnection"], projectId: "p2",
    messageCount: 4,
  },
  {
    id: "em6", subject: "Referral — Rick Sandoval",
    snippet: "Hey Jake, just referred my neighbor Rick Sandoval to you guys. He's got a great south-facing roof...",
    from: "Mike Martinez", fromEmail: "mikem@gmail.com",
    to: ["jake@shorebreakelectric.com"],
    date: "2026-02-14T11:05:00", unread: false, starred: false,
    labels: ["referral"], customerId: "c7",
    messageCount: 1,
  },
  {
    id: "em7", subject: "Coastal Brew — Site Visit Confirmation",
    snippet: "Hi Tom, confirmed for Wednesday May 7th at 10am. I'll have the building manager available to...",
    from: "Coastal Brew Owner", fromEmail: "owner@coastalbrewco.com",
    to: ["tom@shorebreakelectric.com"],
    date: "2026-05-02T11:30:00", unread: false, starred: false,
    labels: ["assessment"], projectId: "p4", customerId: "c8",
    messageCount: 3,
  },
];

export const dashboardStats: DashboardStats = {
  totalRevenue: 374100,
  revenueChange: 18.4,
  activeProjects: 6,
  activeProjectsChange: 2,
  pendingInstalls: 3,
  completedThisMonth: 1,
  completedChange: 0,
  leadsThisMonth: 2,
  leadsChange: 1,
  avgProjectValue: 47750,
  installedKW: 185.4,
};

export const monthlyRevenue = [
  { month: "Nov", revenue: 28000, projects: 3 },
  { month: "Dec", revenue: 35000, projects: 4 },
  { month: "Jan", revenue: 42000, projects: 4 },
  { month: "Feb", revenue: 38000, projects: 5 },
  { month: "Mar", revenue: 55000, projects: 6 },
  { month: "Apr", revenue: 61000, projects: 7 },
];

export const pipelineByStage = [
  { stage: "Lead", count: 2, value: 0 },
  { stage: "Proposal", count: 1, value: 78000 },
  { stage: "Assessment", count: 1, value: 64500 },
  { stage: "Engineering", count: 1, value: 28900 },
  { stage: "Permitting", count: 1, value: 87000 },
  { stage: "Installation", count: 1, value: 42500 },
  { stage: "Inspection", count: 1, value: 42000 },
  { stage: "Complete", count: 1, value: 31200 },
];
